# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import books_pb2 as books__pb2


class BookServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.List = channel.unary_unary(
        '/books.BookService/List',
        request_serializer=books__pb2.Empty.SerializeToString,
        response_deserializer=books__pb2.BookList.FromString,
        )
    self.Insert = channel.unary_unary(
        '/books.BookService/Insert',
        request_serializer=books__pb2.Book.SerializeToString,
        response_deserializer=books__pb2.Empty.FromString,
        )
    self.Get = channel.unary_unary(
        '/books.BookService/Get',
        request_serializer=books__pb2.BookIdRequest.SerializeToString,
        response_deserializer=books__pb2.Book.FromString,
        )
    self.Delete = channel.unary_unary(
        '/books.BookService/Delete',
        request_serializer=books__pb2.BookIdRequest.SerializeToString,
        response_deserializer=books__pb2.Empty.FromString,
        )
    self.Watch = channel.unary_stream(
        '/books.BookService/Watch',
        request_serializer=books__pb2.Empty.SerializeToString,
        response_deserializer=books__pb2.Book.FromString,
        )


class BookServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def List(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Insert(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Watch(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BookServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'List': grpc.unary_unary_rpc_method_handler(
          servicer.List,
          request_deserializer=books__pb2.Empty.FromString,
          response_serializer=books__pb2.BookList.SerializeToString,
      ),
      'Insert': grpc.unary_unary_rpc_method_handler(
          servicer.Insert,
          request_deserializer=books__pb2.Book.FromString,
          response_serializer=books__pb2.Empty.SerializeToString,
      ),
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=books__pb2.BookIdRequest.FromString,
          response_serializer=books__pb2.Book.SerializeToString,
      ),
      'Delete': grpc.unary_unary_rpc_method_handler(
          servicer.Delete,
          request_deserializer=books__pb2.BookIdRequest.FromString,
          response_serializer=books__pb2.Empty.SerializeToString,
      ),
      'Watch': grpc.unary_stream_rpc_method_handler(
          servicer.Watch,
          request_deserializer=books__pb2.Empty.FromString,
          response_serializer=books__pb2.Book.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'books.BookService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
