# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import books_pb2 as books__pb2


class BookServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.List = channel.unary_unary(
        '/books.BookService/List',
        request_serializer=books__pb2.Empty.SerializeToString,
        response_deserializer=books__pb2.BookList.FromString,
        )


class BookServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def List(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BookServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'List': grpc.unary_unary_rpc_method_handler(
          servicer.List,
          request_deserializer=books__pb2.Empty.FromString,
          response_serializer=books__pb2.BookList.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'books.BookService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
